version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1425
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media


    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY=django-insecure-tlg0ppn!(f(-4suj7-9j(lyj&ev5afd4e=g#3x+#+)s=qwr*t#
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,'*'

    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
